### ISSUE TITLE
Member "keyExistsJson" not found or not visible after argument-dependent lookup in contract Vm.

### ISSUE THREAD

**Issue by Krishnakumarskr** [OpenZeppelin/openzeppelin-foundry-upgrades#35] opened 2024-03-25 16:48 UTC
Getting this error on compiling for the very first time after installing it.

**Comment by ericglau** [comment] 2024-03-28 15:46
Duplicate of https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/33 -- please see my comment in that issue.

@Magicking If you are still encountering errors with forge-std v1.8.0 or higher, please open a separate issue with the errors you are receiving.

**Closed by ericglau** 2024-03-28 15:46 UTC
